steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'pythonapp',
           '--image', 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA',
           '--region', 'us-east4',
           '--platform', 'managed',
           '--allow-unauthenticated',
           '--port', '5000',
           '--set-env-vars=FLASK_APP=app.py']
images:
  - 'gcr.io/$PROJECT_ID/sua-imagem:$SHORT_SHA'
